WEEK 3 BILAL GOKTAS
HackYourHomework/databases-class38 pull request #42
Opened 2022-09-06 19:53 UTC by bilalgoktas

2022-09-11 08:11 UTC, acadavid requested changes
@bilalgoktas Good progress! Please correct the normalization exercise and I will approve.

2022-09-11 08:11 UTC, acadavid commented on Week3/homework/exercise1.md
> +- dinner_id (fk ref to dinners)
This would mean that if a member is attending multiple dinners, I need to repeat all of the user data. You need an auxiliary table for this relationship.

2022-09-11 08:11 UTC, acadavid commented on Week3/homework/exercise1.md
> +- data
What is data? I guess `date`?

2022-09-11 08:11 UTC, acadavid commented on Week3/homework/transaction.js
> +            "START TRANSACTION;",
Great job! 🎉

2022-09-11 08:11 UTC, acadavid commented on Week3/homework/exercise3_injection.js
> +  // to name input = ' OR 1=1'
Nice!

2022-09-11 08:11 UTC, acadavid commented on Week3/homework/exercise3_injection.js
> +      "SELECT Population FROM ${Country} WHERE Name = ? and code = ?", [name, code],
👍 Looks good!

2022-09-11 08:11 UTC, acadavid commented on Week3/homework/mongodb/index.js
> +require('dotenv').config()
Good job with all the exercises in this file! 💪

2022-09-11 22:30 UTC, bilalgoktas commented on Week3/homework/exercise1.md
> +- dinner_id (fk ref to dinners)
Hi Alejo! Please find the commit below.

2022-09-11 22:30 UTC, bilalgoktas commented on Week3/homework/exercise1.md
> +- data
Hi Alejo! Please find the commit below.

2022-09-18 13:56 UTC, acadavid approved these changes

2022-12-13 20:29 UTC, closed without merging