Week 1 Homework Bilal Goktas
HackYourHomework/databases-class38 pull request #7
Opened 2022-08-23 09:55 UTC by bilalgoktas

2022-08-28 09:56 UTC, acadavid requested changes
@bilalgoktas Good job. Please correct the type of the fields from `TEXT` to `VARCHAR` and I will approve your PR.

2022-08-28 09:56 UTC, acadavid commented on meetupdb.js
> +connection.query('CREATE TABLE Invitee (invitee_no INT, invitee_name TEXT, invited_by TEXT)', (error, results, fields) => {
`TEXT` is a type for very large texts. Invitee names are likely to be people names, which would hardly be more than 100 characters. A better type for this is `VARCHAR`. Please update the PRs correcting this type for all tables.

Also I see you added a primary key to some tables. Might as well just add it too all of them! 💪

2022-08-28 09:56 UTC, acadavid commented on meetupdb.js
> +  connection.query('CREATE TABLE Room (room_no INT, room_name TEXT, floor_number INT, PRIMARY KEY (room_no))', (error, results, fields) => {
Check comment above about `TEXT` type.

2022-08-28 09:56 UTC, acadavid commented on meetupdb.js
> +  connection.query('CREATE TABLE Meeting (meeting_no INT, meeting_title TEXT, starting_time DATETIME, ending_time DATETIME, room_no INT, FOREIGN KEY (room_no) REFERENCES Room(room_no))', (error, resu
Nice touch adding  a foreign key

2022-08-28 09:56 UTC, acadavid commented on worlddb.js
> +connection.end();
All these queries are correct. Well done!

2022-08-30 11:40 UTC, bilalgoktas commented
> 

@acadavid Thanks a lot for valuable feedback. I have made the necessary changes accordingly.

2022-09-04 05:49 UTC, acadavid approved these changes

2022-12-13 20:29 UTC, closed without merging